Feat/presale updates
JubiDAO/protocol pull request #14
Opened 2022-06-20 16:31 UTC by T04435

This PR adds new Features to the `Presale.sol` Contract

### Features
- #12 
- #13

### Tested
+ Invite Codes
        ✔ Invite code can only be used by a single wallet
        ✔ Investor investment can not exceed Invite Code maxInvestment
        ✔ Invalid invite codes are not accepted
        ✔ Mismatched invite hash and merkle proof should fail
        ✔ Not allowed to invest less than minimum investment
        ✔ Allowed to invest less than minimum at the time as long as, all up is more than minInvestment
+ Refunds
        ✔ Token are swap after round is closed and hurdle is not met
        ✔ Investor can get refunds after round close and hurdle is not meet
        ✔ Investor can get refunds when investing multiple times after round close and hurdle is not meet

! Please let me know if you see a need for more testing, happy to add them.

### Dapp
Local deploy script will generate all files that need to be imported to `public/data` after running `yarn local-deploy` you will get the list of files paths

```bash
// contains the actual invite-codes ready to import in a sheet
File create: [path_to_repo]/saftely-protocol/gen/invite-codes_local.csv
// use this one to get data from keccak256(code).toString("hex")
File create: [path_to_repo]/saftely-protocol/gen/invite-codes_local.json
// merkle
File create: [path_to_repo]/saftely-protocol/gen/merkle_local.json
```

### Extra 🤓
Came across this https://docs.soliditylang.org/en/v0.8.15/natspec-format.html
Started adding all the comments, if anyone has used it before please feel free to add best practices
IMO this will improve the UX when interacting with Metamask(other) as it is meant to add Metadata see https://raw.githubusercontent.com/aragon/radspec/master/.github/assets/metamask_example.png

### Question
Would #9  be a blocker for this one.

2022-06-21 05:55 UTC, jsuresh requested changes

2022-06-21 05:55 UTC, jsuresh commented on contracts/Presale.sol
> + * @notice You can use this Contract to Fund `daoMultisig` with `raiseToken` to launch their project. In return you will get `issuedToken` once `hurdle` is meet and round is closed; in case the hurdl
Formatting (lines too long)

2022-06-21 05:55 UTC, jsuresh commented on contracts/Presale.sol
> + * @author @T04435
delete - captured in git history

2022-06-21 05:55 UTC, jsuresh commented on contracts/Presale.sol
> + * @title Contract to Fund start ups
@ashvds - what's a better title comment? Comments here are important as it forms part of the documentation on the system.

I suggest 

'@title Capture economics of a funding round'

2022-06-21 05:55 UTC, jsuresh commented on contracts/Presale.sol
> + * @notice You can use this Contract to Fund `daoMultisig` with `raiseToken` to launch their project. In return you will get `issuedToken` once `hurdle` is meet and round is closed; in case the hurdl
@notice Funds `daoMultisig` with `raiseToken` once `hurdle` is met.
Funders will get `issuedToken` on a round close, once vesting conditions are met.

If the hurdle isn't cleared, funders can claim back their initial investment.

2022-06-21 05:55 UTC, jsuresh commented on contracts/Presale.sol
> +        if (claimedInvites[inviteCode] != address(0)) {
Remove if, isn't this just

`require(claimedInvites[inviteCode] == account || claimedInvites[inviteCode] == address(0) , "Presale: You can only invest with one wallet per invite code");`

Slight gas efficiency, and IMHO clearer

2022-06-21 05:55 UTC, jsuresh commented on contracts/Presale.sol
> +        require(amount > 0, "Presale: You have invest up to your limit");
Any reason for this extra require? Won't the remaining logic just work with `amount == 0`

As a pattern, require for things that are invariants, any nice to have checks should be handled in the frontend.

2022-06-21 05:55 UTC, jsuresh commented on contracts/Presale.sol
> +    ///   provide 0 to use timestamp
Generally, an anti-pattern to do cute stuff like if 0 use current timestamp. Makes code hard to reason about.

If you want an invariant which is calculateClaimableNow(), then write that method.

Given this is only used in one place, I think it's fine to just pass in block.timestamp and expect callers to get this right.

2022-06-21 05:55 UTC, jsuresh commented on contracts/Presale.sol
> +        uint256 calculationTimestamp = block.timestamp;
delete as per documentation comment

2022-06-21 05:55 UTC, jsuresh commented on contracts/Presale.sol
> +     *  if hurdle was not meet this can be used as a refundFor which will transfer all your investment to `account`
Reword the second sentence.

`if hurdle was not met on round close, funders will call claimFor to get their initial investment back`

2022-06-21 05:55 UTC, jsuresh commented on contracts/Presale.sol
> +        // update so it includes the Price/setup
Delete comment (don't think it makes sense)

2022-06-21 05:55 UTC, jsuresh commented on contracts/Presale.sol
> +        /// @dev when round is closed if Hurdle is meet transfer funds to daoMultisig
@dev and the tripple slash is only for doxygen style comments (so public methods, contracts etc.) Have a read of the solidity style guide @T04435 

Change to normal comment

2022-06-21 05:55 UTC, jsuresh commented on contracts/Presale.sol
> +            /// @dev when round is closed if Hurdle is NOT meet set the issuedToken to raiseToken so claimFor acts as a "refundFor"
// when the round is closed if Hurdle is NOT met set the issuedToken to raiseToken and remove any vesting so funders can call claimFor to refund their initial investment

2022-06-21 05:55 UTC, jsuresh commented on scripts/deploys/local.ts
> -  console.log('*** INVITE CODES ***');
Both of these are useful in local dev. Where are they output now?

2022-06-21 05:55 UTC, jsuresh commented on .gitignore
> +gen/*
keeping generated files seems... odd? Bit more context

2022-06-21 05:55 UTC, jsuresh commented on scripts/generate-invite-codes.ts
> +const inviteCodesInputs: Array<InviteCodeConfig> = [
shouldn't this be caller config (like the old version, which only had the total number which was albeit simpler)?

Or is this a local dev only script? Given the dapp will have to generate and prompt user to d/l a set of invite codes before the contract is deployed.

2022-06-21 05:55 UTC, jsuresh commented on scripts/generate-invite-codes.ts
> +    json = json.concat(
any reason we are building up a JSON file via string building as opposed to just making a JSON file then calling JSON.stringify?

2022-06-21 05:55 UTC, jsuresh commented on test/presale-tests.ts
> +  let PRESALE: Presale;
lower case, as per existing test style please

2022-06-21 05:55 UTC, jsuresh commented on test/presale-tests.ts
> +import { expect } from "chai";
This file is basically impossible to review as it's mostly formatting changes.

Can you please revert formatting changes and put forward a minimal diff.

2022-06-23 05:51 UTC, ashvds commented on contracts/Presale.sol
> + * @title Contract to Fund start ups
'@title Token management for a funding round'

more than just economics since there's vesting

2022-06-23 05:56 UTC, ashvds commented on contracts/Presale.sol
> +     * @notice Will deposit `amount` of token `raisedToken` for this Presale Round
```suggestion
     * @notice Deposit `amount` of token `raiseToken` for this Round. Requires valid 'amount' as per 'inviteCode'
```

2022-06-23 06:05 UTC, ashvds commented on contracts/Presale.sol
> +     *  @notice When round is closed if `hurdle` was meet you can claim your current allocation
```suggestion
     *  @notice Claim available allocation of 'issuedToken' if round is closed ( 'isOpen'=false ) and  `hurdle` amount was met 
```

2022-06-23 06:08 UTC, ashvds commented on contracts/Presale.sol
> +     *  if hurdle was not meet this can be used as a refundFor which will transfer all your investment to `account`
```suggestion
     *  If the round is closed and hurdle was not met, claimFor will return invested amount of 'raiseToken' to 'account'
```

2022-06-24 09:43 UTC, jsuresh requested changes

2022-06-24 09:43 UTC, jsuresh commented on .gitignore
> +gen/*
@T04435 ?

2022-06-24 09:43 UTC, jsuresh commented on contracts/Presale.sol
> + * @notice Funds `daoMultisig` with `raiseToken` once round is closed and `hurdle` is met.
@T04435 - worth creating an issue saying we need better names for daoMultisig, raiseToken and issueToken

2022-06-24 09:43 UTC, jsuresh commented on contracts/Presale.sol
> +    function calculateClaimableNow(address account) public view returns (uint256, uint256) {
We should delete this.

HOWEVER, can you make an issue, and delete this as a separate PR, as to not block progress on this PR. This method does make it easier to parse all the tests so would be far easier to understand as a follow up fixup PR than changing this.

2022-06-24 09:43 UTC, jsuresh commented on package.json
> +    "local-gen": "hardhat run --network localhost scripts/generate-invite-codes.ts",
s/local-gen/local-gen-invite-codes/g

2022-06-24 09:43 UTC, jsuresh commented on scripts/generate-invite-codes.ts
> +const inviteCodesInputs: Array<InviteCodeConfig> = [
@T04435 ?

2022-06-24 09:43 UTC, jsuresh commented on scripts/generate-invite-codes.ts
> +const inviteCodesInputs: Array<InviteCodeConfig> = [
Fine if the resolution is to create an issue for now (or because this is only meant to be used in local dev, doesn't matter)

2022-06-24 09:43 UTC, jsuresh commented on test/presale-tests.ts
> +  let INVESTOR3: Signer;
Delete these, as the only reason they exist, is to meet the hurdle, which we can do by having sufficient min/max or lower hurdle in tests (makes for clearer tests).

I suggest making an issue and doing as a follow up PR to speed up landing this, plus, I suspect this will be a lot easier once you update the data model for invite codes (see later comment) - you may even do both together.

As a rule of thumb, tweak tests data to make tests clearer/simpler than adding extra actions. You want min actions to test conditions/share meaning of tests with other devs.

--- Below here isn't relevant for this PR, but relevant in general ---

Orthogonally - you should follow the naming pattern of real names. It's the pattern so worth following for consistency if nothing else.

The reason to use names in the tests, is it helps the tests read more like english. 

Ash does XXX, Jeeva does YYY.

Could you please keep this pattern. If you want to make it clear that this person is an investor (and that's important for the test), name as joe_investor, jane_investor etc.

Also, lower case please (to keep with the existing style).

2022-06-24 09:43 UTC, jsuresh commented on test/presale-tests.ts
> +  const skipNInvites = (invitesToSkip: number): void => {
NOTE: Please do as a follow up as to not block this PR (make an issue for now)

Delete, this is used to hack around the fact you have 2 sets of invite codes of different min/max.

When you have to do stuff like this, it's a smell your original data structures are wrong and needs a rethink.

My intuition is that 2 lists (each with a different min/max) will make your tests easier. You can then have `nextInviteSmallBag()` and `nextInviteBigBag()` as the well-named helpers

Please take the above as my intuition after a few seconds thinking about it. The principal is with the right data structures, the code should be obvious, and when you have the wrong data structures, you end up with weird hacks like this.

2022-06-24 09:43 UTC, jsuresh commented on test/presale-tests.ts
> +      await presale.depositFor(await jeeva.getAddress(), toAtto(100), ...nextInvite());
What did you change in this test?

2022-06-24 09:43 UTC, jsuresh commented on contracts/Presale.sol
> +        // check balance in the token is
Not sure this comment makes sense/is still relevant.

2022-06-24 09:50 UTC, jsuresh commented on scripts/deploys/local.ts
> -  console.log('*** INVITE CODES ***');
@T04435 please address comment

2022-06-26 02:51 UTC, T04435 commented on test/presale-tests.ts
> +      await presale.depositFor(await jeeva.getAddress(), toAtto(100), ...nextInvite());
The invite had a minInvestment of 100, so original test(50) would have failed with `"Presale: Can not invest less than minimum amount"`

2022-06-26 02:51 UTC, T04435 commented on contracts/Presale.sol
> +        // check balance in the token is
removed

2022-06-26 02:51 UTC, T04435 commented on test/presale-tests.ts
> +  let INVESTOR3: Signer;
#19

2022-06-26 02:51 UTC, T04435 commented on test/presale-tests.ts
> +  const skipNInvites = (invitesToSkip: number): void => {
#20

2022-06-26 02:51 UTC, T04435 commented on package.json
> +    "local-gen": "hardhat run --network localhost scripts/generate-invite-codes.ts",
done

2022-06-26 02:51 UTC, T04435 commented on contracts/Presale.sol
> +    function calculateClaimableNow(address account) public view returns (uint256, uint256) {
#21

2022-06-26 02:51 UTC, T04435 commented on contracts/Presale.sol
> + * @notice Funds `daoMultisig` with `raiseToken` once round is closed and `hurdle` is met.
#22

2022-06-26 03:02 UTC, T04435 commented on test/presale-tests.ts
> +      expect(await presale.totalAllocated()).eql(HARD_CAP);
Changes
- 990 => 9900
- 100 => 1000
- 10 => 100

Adds a new check, hard cap is reached => `      expect(await presale.totalAllocated()).eql(HARD_CAP);
`

2022-06-26 03:05 UTC, T04435 commented on test/presale-tests.ts
> +      await presale.depositFor(await jeeva.getAddress(), HARD_CAP, ...nextInvite());
Updates so it uses the HARD_CAP variable instead of `toAtto(1000)`

2022-06-26 08:23 UTC, jsuresh commented on contracts/Presale.sol
> +        require(amount > 0, "Presale: You have invest up to your limit");
Okay, leave-in (I'm resolving as such). 

FWIW There are 3 cases and the pattern I'd like to push is require capture invariants (eg. preconditions), with any nice to have useability checks pushed to the DApp. (@ashvds and @samfroggy for visibility/FYI). Moving debate on this to TG.

1. Direct contract interaction via etherscan (super user mode, no need to optimise for usability here)
2. Interaction via the DApp (in which case, the DApp should report the error)
3. Interaction via the DApp, however when a transaction is submitted, the user has an allocation, by the time their transaction is mined, they have lost it.

It's only (3) which is a real usability issue, which (IMHO) should and can be handled via appropriate DApp logic. It's worth investing in building this FE infrastructure up, as once we do, we can re-use it easily. [@timbod7 ](https://github.com/timbod7) has been building some of this up and would be happy to advise I'm sure :)

2022-06-26 09:04 UTC, jsuresh commented on contracts/Presale.sol
> +    /// @param timestamp => can be used to calculate claimable amount in a time other than block.timestamp
Might need another round/discussion review post merging, on the surface it doesn't seem right that we check claimFor by calling calculateClaimable.

Tests should have a simpler model of what's claimable at some point in time, otherwise, we aren't actually verifying anything. FYI @ashvds please keep this in mind as we push contracts into the future (and may need to use this heuristic to fixup the tests)

2022-06-26 09:10 UTC, jsuresh approved these changes
LGTM :) merge away @T04435

2022-06-27 01:21 UTC, merged

2022-06-28 00:22 UTC, samfroggy commented
LGTM (Just getting across all changes)
Does the branch need to be deteled @T04435 ?